### ISSUE TITLE
Meta-issue for tracking action-angle transformation functionality

### ISSUE THREAD

**Issue by adrn** [GalacticDynamics/galax#191]
- [ ] O2GF (should be "easy", and @jnibauer is going to have a go at it!)
- [ ] Staeckel Fudge (@adrn started this but got stuck on some math. Maybe we can convince @jls713 to come help :))
- [ ] Spherical action solver
- [ ] 1D action solver
